### PR TITLE
Added support for tags in the StatsD collector

### PR DESCRIPTION
**Pull request by dsantang**
I've seen that the tag support has currently been implemented only for the InfluxDB collector, so I'd like to try giving my contributon by adding it to the StatsD collector as well.

### CODE REVIEW

**Comment by lyrixx** [comment]
Thanks @dsantang for this new feature. I appreciate it.

I never used statsd tags, do you have any docs about that? thanks.

**Comment by dsantang** [comment]
Hey @lyrixx, sorry for the delayed response.
It is actually only (I think) for the Telegraf - StatsD implementation.
On this page, the "Introducing Influx StatsD" section shows how to tag StatsD metrics:

https://www.influxdata.com/getting-started-with-sending-statsd-metrics-to-telegraf-influxdb/

**Comment by lyrixx** [comment]
Ah Ok. that's why I never hear about that feature.
Because this feature is not part of the standard, I'm a bit reluctant to add it.
May be we can add a new Collector: `Telegraph`. What do you think ?

**Comment by dsantang** [comment]
Yeah, that way we can better separate the concerns.
Altho that will lead to code duplication* **IF** we do not want to re-build the `StatsD` collector as well.
What approach would you suggest?

*(the class `Telegraf` will basically have the same code of `StatsD` with in addition the Tags logic)

**Comment by lyrixx** [comment]
If it's possible to extends the code, let's do this. 
It it's not possible, I'm totally fine with code duplication.

**Comment by lyrixx** [comment]
:+1:

**Comment by dsantang** [comment]
Thanks for your review @lyrixx,  do you know if this will be merged any time soon?

**Comment by lyrixx** [comment]
Thanks @dsantang for working on this feature, this is much appreciated.

**Comment by lyrixx** [comment]
Hello. I just pushed a new release: [v2.2.0](https://github.com/beberlei/metrics/releases/tag/v2.2.0)

**Pull request closed without merging**
