### PR TITLE
Use official InfluxDB library

### PR DESCRIPTION
**Pull request by samvdb**
Topic says it all!

### CODE REVIEW

**Comment by andrejbaran** [comment]
@lyrixx @samvdb Hey guys, If I may, I'm all for making this happen but I believe it can be done without introducing a breaking change by allowing both `influxdb-sdk` and the official `influxdb-php` by having an interface for influxdb "client" and adapters (in a sense) for both of them.

@samvdb would you have time to work on it? If not I can take over and finish this (with you being credites of course as I already forked your fork)

I'd love to hear your thoughts.

**Comment by lyrixx** [comment]
I would use a different approach (to not break the BC).

1. create a new InfluxDB (and let the existing one intact) 
2. I  the constructuctor, add something like `if (!class_exist(Official\InfluxDB\Clien::class) { throw new RuntimeException('package influxdb/influxdb-php is required to use this Collector')`
3. enjoy

So there is no need for an extra interface

**Comment by andrejbaran** [comment]
@lyrixx You mean new InfluxDB collector?

**Comment by lyrixx** [comment]
@andrejbaran yes

**Comment by andrejbaran** [comment]
@lyrixx alright I will try to do it asap

**Comment by andrejbaran** [comment]
@lyrixx I guess we can close this PR since there will be a new one, right?

**Comment by lyrixx** [comment]
@andrejbaran I prefer to wait :)

**Pull request closed without merging**
