### PR TITLE
Add DogStatsD support

### PR DESCRIPTION
**Pull request by eexit**
Should satisfy #34.

I'm not very familiar with the Symfony stuff so don't hesitate to bring your contribution or even globally.

Thanks,

### CODE REVIEW

**Comment by lyrixx** [comment]
This looks good to me. But I'm not very comfortable with having two ways to do the same things. There is now 2 ways to add tags.

Is it a real use case to send different tags with the same Collector?

**Comment by eexit** [comment]
Thanks for the review @lyrixx!

> But I'm not very comfortable with having two ways to do the same things. There is now 2 ways to add tags.

I agree with that but thing is that there's no normalized way to add tags with metric collectors.. Looks like each vendor has its own way to support them.

> Is it a real use case to send different tags with the same Collector?

Absolutely. We do at CareerBuilder.

Here's the DataDog [doc](http://docs.datadoghq.com/guides/metrics/#tags):

> Tags are a way of adding dimensions to metrics, so they can be sliced, diced, aggregated and compared on the front end. Suppose we wanted to measure the performance of two algorithms in the real world.

**Comment by lyrixx** [comment]
Thanks for your work on this new feature!

**Comment by lyrixx** [comment]
I just released v2.4.0 ;)

Have a nice day.

**Pull request merged**
