### PR TITLE
Introducing: InlineTaggableGaugeableNullCollector

### PR DESCRIPTION
**Pull request by jandeschuttere**
For those who want the benefit of tags on metrics and still have typed support

### CODE REVIEW

**Comment by jandeschuttere** [comment]
thanks @becoded for a couple of small, yet important, remarks.

**Comment by jandeschuttere** [comment]
Hi @lyrixx,

I hope you are one of the main maintainers of this repository, If not apologies 🙇 , I just wanted to catch your attention and hope this can be merged.
Any feedback in case you aren't agreeing with this PR is welcome.

Cheers

**Comment by becoded** [comment]
@lyrixx what needs to happen to get this merged in?

**Comment by becoded** [comment]
@lyrixx any news on this?

**Comment by jandeschuttere** [comment]
@lyrixx can we get this merged?

**Review by lyrixx — APPROVED** [review]

**Comment by lyrixx** [comment]
@jandeschuttere Thansk for your first PR. And I'm sorry for this delay

**Pull request merged**
